# Generated by Django 6.0 on 2026-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=20, null=True),
        ),
    ]
